//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_presentation.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TASK_PRESENTATIONEntities : DbContext
    {
        public TASK_PRESENTATIONEntities()
            : base("name=TASK_PRESENTATIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
        public virtual DbSet<TIPO_FUNDO> TIPO_FUNDO { get; set; }
        public virtual DbSet<TIPO_IMPRESSAO> TIPO_IMPRESSAO { get; set; }
        public virtual DbSet<TIPO_MOLDURA> TIPO_MOLDURA { get; set; }
        public virtual DbSet<TIPO_VIDRO> TIPO_VIDRO { get; set; }
        public virtual DbSet<QUADRO_OS> QUADRO_OS { get; set; }
    }
}
