//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_presentation.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUADRO_OS
    {
        public int CD_QUADRO { get; set; }
        public Nullable<int> CD_OS { get; set; }
        public int VL_ALTURA { get; set; }
        public int VL_LARGURA { get; set; }
        public Nullable<int> CD_MOLDURA { get; set; }
        public Nullable<int> CD_VIDRO { get; set; }
        public Nullable<int> CD_IMPRESSAO { get; set; }
        public Nullable<int> CD_FUNDO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual TIPO_FUNDO TIPO_FUNDO { get; set; }
        public virtual TIPO_IMPRESSAO TIPO_IMPRESSAO { get; set; }
        public virtual TIPO_MOLDURA TIPO_MOLDURA { get; set; }
        public virtual TIPO_VIDRO TIPO_VIDRO { get; set; }
    }
}
