//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_presentation.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CD_USUARIO { get; set; }
        public string DS_NOME { get; set; }
        public string DS_SENHA_CRIPTOGRAFADA { get; set; }
        public Nullable<int> CD_CARGO { get; set; }
    }
}
